export const SEED_MENU_ITEMS = [
  {
    id: 'm1',
    name: 'Grilled Bangus',
    price: 220,
    category: 'Mains',
    description: 'Milkfish stuffed with tomatoes and onions, grilled to order.',
  },
  {
    id: 'm2',
    name: 'Sizzling Sisig',
    price: 195,
    category: 'Mains',
    description: 'Chopped pork belly sizzled with onions, chili and calamansi.',
  },
  {
    id: 'm3',
    name: 'Ribeye Steak',
    price: 385,
    category: 'Mains',
    description: 'Grilled ribeye served with mushroom gravy and vegetables.',
    modifierGroups: [
      {
        id: 'g1',
        name: 'Cooking Level',
        type: 'single_select',
        required: true,
        options: [
          { id: 'o1', label: 'Rare', priceDelta: 0 },
          { id: 'o2', label: 'Medium', priceDelta: 0 },
          { id: 'o3', label: 'Well Done', priceDelta: 0 },
        ],
      },
      {
        id: 'g2',
        name: 'Add-ons',
        type: 'multi_select',
        options: [
          { id: 'o4', label: 'Extra Rice', priceDelta: 25 },
          { id: 'o5', label: 'Fried Egg', priceDelta: 20 },
        ],
      },
    ],
  },
  {
    id: 'm4',
    name: 'Chicken Adobo',
    price: 175,
    category: 'Mains',
    description: 'Classic chicken braised in soy, vinegar, and garlic.',
  },
  {
    id: 'a1',
    name: 'Lumpiang Shanghai',
    price: 120,
    category: 'Appetizers',
    description: 'Crispy pork spring rolls, 6 pieces, with sweet chili sauce.',
  },
  {
    id: 'a2',
    name: 'Calamares',
    price: 165,
    category: 'Appetizers',
    description: 'Battered squid rings, fried and served with garlic mayo.',
  },
  {
    id: 'a3',
    name: 'Tokwa at Baboy',
    price: 140,
    category: 'Appetizers',
    description: 'Fried tofu and pork in soy vinegar dip.',
  },
  {
    id: 'a4',
    name: 'Ensaladang Talong',
    price: 95,
    category: 'Appetizers',
    description: 'Grilled eggplant salad with tomatoes and salted egg.',
  },
  {
    id: 's1',
    name: 'Garlic Rice',
    price: 45,
    category: 'Sides',
    description: 'Fried rice tossed in garlic.',
    modifierGroups: [
      {
        id: 'g3',
        name: 'Add-ons',
        type: 'multi_select',
        options: [{ id: 'o6', label: 'Extra Egg', priceDelta: 20 }],
      },
    ],
  },
  {
    id: 's2',
    name: 'Steamed Rice',
    price: 30,
    category: 'Sides',
    description: 'Plain steamed white rice.',
  },
  {
    id: 's3',
    name: 'Mixed Vegetables',
    price: 85,
    category: 'Sides',
    description: 'Seasonal vegetables sauteed in oyster sauce.',
  },
  {
    id: 's4',
    name: 'Mashed Potato',
    price: 75,
    category: 'Sides',
    description: 'Creamy mashed potatoes with butter.',
  },
  {
    id: 'd1',
    name: 'Iced Tea',
    price: 55,
    category: 'Drinks',
    description: 'House-brewed iced tea, refillable.',
  },
  {
    id: 'd2',
    name: 'Calamansi Juice',
    price: 60,
    category: 'Drinks',
    description: 'Fresh calamansi juice, sweetened.',
  },
  {
    id: 'd3',
    name: 'Buko Shake',
    price: 85,
    category: 'Drinks',
    description: 'Fresh young coconut blended shake.',
  },
  {
    id: 'd4',
    name: 'Soda',
    price: 50,
    category: 'Drinks',
    description: 'Bottled soft drink, choice of flavor.',
  },
  {
    id: 'e1',
    name: 'Leche Flan',
    price: 75,
    category: 'Desserts',
    description: 'Creamy caramel custard.',
  },
  {
    id: 'e2',
    name: 'Halo-Halo',
    price: 130,
    category: 'Desserts',
    description: 'Shaved ice with mixed sweets, leche flan and ube.',
  },
  {
    id: 'e3',
    name: 'Turon',
    price: 65,
    category: 'Desserts',
    description: 'Caramelized banana rolls, 3 pieces.',
  },
  {
    id: 'e4',
    name: 'Buko Pandan',
    price: 80,
    category: 'Desserts',
    description: 'Coconut and pandan gelatin dessert.',
  },
];
