export const SEED_MENU_ITEMS = [
  {
    id: 'm1',
    name: 'Pork Barbeque',
    price: 35,
    category: 'Mains',
    description: 'Grilled pork with barbecue sauce.',
    icon: '🍖',
  },
  {
    id: 'm2',
    name: 'Lomi',
    price: 80,
    category: 'Mains',
    description: 'Filipino egg noodle soup.',
    icon: '🍜',
  },
  {
    id: 'm3',
    name: 'Chami',
    price: 80,
    category: 'Mains',
    description: 'Filipino stir-fried noodles.',
    icon: '🍝',
  },
  {
    id: 'm4',
    name: 'Sisig',
    price: 90,
    category: 'Mains',
    description: 'Chopped pork with onions and chili.',
    icon: '🔥',
  },
  {
    id: 'm5',
    name: 'Chicken Inasal',
    price: 90,
    category: 'Mains',
    description: 'Grilled chicken with spices.',
    icon: '🍗',
  },
  {
    id: 'm6',
    name: 'Liempo',
    price: 90,
    category: 'Mains',
    description: 'Grilled pork belly.',
    icon: '🥩',
  },
  {
    id: 'e1',
    name: 'Leche Flan',
    price: 100,
    category: 'Desserts',
    description: 'Caramel custard.',
    icon: '🍮',
  },
  {
    id: 'e2',
    name: 'Ice Cream',
    price: 50,
    category: 'Desserts',
    description: 'Vanilla ice cream.',
    icon: '🍦',
  },
  {
    id: 'd1',
    name: 'Coke',
    price: 20,
    category: 'Drinks',
    description: 'Cold cola drink.',
    icon: '🥤',
  },
  {
    id: 'd2',
    name: 'Sprite',
    price: 20,
    category: 'Drinks',
    description: 'Lemon-lime soda.',
    icon: '🥤',
  },
  {
    id: 'd3',
    name: 'Iced Tea',
    price: 20,
    category: 'Drinks',
    description: 'Chilled tea.',
    icon: '🧋',
  },
  {
    id: 'd4',
    name: 'Mineral Water',
    price: 20,
    category: 'Drinks',
    description: 'Bottled water.',
    icon: '💧',
  },
  {
    id: 's1',
    name: 'Rice',
    price: 20,
    category: 'Sides',
    description: 'Steamed white rice.',
    icon: '🍚',
  },
  {
    id: 's2',
    name: 'Fries',
    price: 50,
    category: 'Sides',
    description: 'Crispy french fries.',
    icon: '🍟',
  },
  {
    id: 's3',
    name: 'Salad',
    price: 50,
    category: 'Sides',
    description: 'Fresh vegetable salad.',
    icon: '🥗',
  },
  {
    id: 's4',
    name: 'Soup',
    price: 40,
    category: 'Sides',
    description: 'Hot vegetable soup.',
    icon: '🍲',
  },
];

export const MENU_CATEGORIES = ['Mains', 'Desserts', 'Drinks', 'Sides'];
